on: pull_request_review
name: Label approved pull requests
jobs:
  labelWhenApproved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
    - name: Label when approved
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "1"
        permissions:
          contents: write
          pull-requests: write 
          issues: read
          packages: none
        GITHUB_TOKEN: ${{ github.token }}
        ADD_LABEL: "approved"
        REMOVE_LABEL: "awaiting%10review"
